app:
  image:
    repository: 'onexc-apps/${project.name}'
    tag: ${project.version}
  nameOverride: ${project.name}
  routing:
    enabled: true 
  product: false
  operator:
    apm:
      enabled: false 
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-document-management-ui"    