app:
  image:
    repository: 'onexc-apps/${project.name}'
    tag: ${project.version}
  routing:
    enabled: true
  operator:
    apm:
      enabled: false  
    keycloak:
      enabled: true
      client: '{"clientId": "{{ .Release.Name }}","enabled": true,"description": "Keycloack client for {{ .Release.Name }}","redirectUris": ["*"],"webOrigins": ["*"],"publicClient": true,"protocol": "openid-connect"}'
      
