app:
  image:
    repository: 'onexc-apps/${project.name}'
    tag: ${project.version}
  nameOverride: ${project.name}
  routing:
    enabled: true
  operator:
    apm:
      enabled: false  
  product: false
  